-- V008__create_mock_national_id_registry.sql
-- MHB-11 / UC-22: Create reusable mock National ID registry for later MBH-12 adapters.

CREATE TABLE IF NOT EXISTS mock_national_id_registry (
    id                             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_number                      VARCHAR(20) UNIQUE NOT NULL,
    full_name                      VARCHAR(255) NOT NULL,
    date_of_birth                  DATE NOT NULL,
    gender                         VARCHAR(20) NOT NULL,
    permanent_address              TEXT NOT NULL,
    issue_date                     DATE NOT NULL,
    expiry_date                    DATE NOT NULL,
    issue_place                    TEXT NOT NULL,
    document_status                VARCHAR(30) NOT NULL,
    front_back_match_status        VARCHAR(30) NOT NULL,
    corner_blur_status             VARCHAR(30) NOT NULL,
    id_quality_status              VARCHAR(30) NOT NULL,
    issue_date_status              VARCHAR(30) NOT NULL,
    expiry_status                  VARCHAR(30) NOT NULL,
    document_identification_status VARCHAR(50) NOT NULL,
    warning_status                 VARCHAR(30) NOT NULL,
    overlay_image_status           VARCHAR(30) NOT NULL,
    open_eyes_status               VARCHAR(30) NOT NULL,
    blurred_face_status            VARCHAR(30) NOT NULL,
    face_validation_status         VARCHAR(30) NOT NULL,
    covered_face_status            VARCHAR(30) NOT NULL,
    face_matching_score            NUMERIC(7, 4) NOT NULL,
    source_provider                VARCHAR(50) NOT NULL,
    source_reference               VARCHAR(100) NOT NULL,
    raw_payload                    JSONB NOT NULL DEFAULT '{}'::jsonb,
    active                         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_mock_national_id_registry_active
    ON mock_national_id_registry (active);

INSERT INTO mock_national_id_registry (
    id_number,
    full_name,
    date_of_birth,
    gender,
    permanent_address,
    issue_date,
    expiry_date,
    issue_place,
    document_status,
    front_back_match_status,
    corner_blur_status,
    id_quality_status,
    issue_date_status,
    expiry_status,
    document_identification_status,
    warning_status,
    overlay_image_status,
    open_eyes_status,
    blurred_face_status,
    face_validation_status,
    covered_face_status,
    face_matching_score,
    source_provider,
    source_reference,
    raw_payload,
    active
) VALUES (
    '024204002908',
    'THÂN VĂN THÀNH',
    DATE '2004-08-12',
    'Nam',
    'TDP My Điền 1 Thị trấn Nếnh, Việt Yên, Bắc Giang',
    DATE '2021-04-27',
    DATE '2029-08-12',
    'CỤC TRƯỞNG CỤC CẢNH SÁT QUẢN LÝ HÀNH CHÍNH VỀ TRẬT TỰ XÃ HỘI',
    'VALID',
    'IDENTICAL',
    'NO',
    'GOOD',
    'GOOD',
    'UNEXPIRED',
    'LIVE_SHOOTING',
    'VALID',
    'NO',
    'YES',
    'NO',
    'VALID',
    'NO',
    98.5720,
    'VNPT_EKYC',
    'UC-22_SYNTHETIC_DEMO_RECORD',
    '{
       "documentType": "Valid",
       "frontBackDocument": "Identical",
       "blurredOrAbsenceOfCorners": "No",
       "idQuality": "Good",
       "issuedDateQuality": "Good",
       "expiryDate": "Unexpired",
       "documentIdentification": "Live shooting",
       "warnings": "Valid",
       "overlayImage": "No",
       "openEyes": "Yes",
       "blurredFace": "No",
       "faceValidation": "Valid",
       "coveredFace": "No",
       "faceMatching": "98.500%"
     }'::jsonb,
    TRUE
)
ON CONFLICT (id_number) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    date_of_birth = EXCLUDED.date_of_birth,
    gender = EXCLUDED.gender,
    permanent_address = EXCLUDED.permanent_address,
    issue_date = EXCLUDED.issue_date,
    expiry_date = EXCLUDED.expiry_date,
    issue_place = EXCLUDED.issue_place,
    document_status = EXCLUDED.document_status,
    front_back_match_status = EXCLUDED.front_back_match_status,
    corner_blur_status = EXCLUDED.corner_blur_status,
    id_quality_status = EXCLUDED.id_quality_status,
    issue_date_status = EXCLUDED.issue_date_status,
    expiry_status = EXCLUDED.expiry_status,
    document_identification_status = EXCLUDED.document_identification_status,
    warning_status = EXCLUDED.warning_status,
    overlay_image_status = EXCLUDED.overlay_image_status,
    open_eyes_status = EXCLUDED.open_eyes_status,
    blurred_face_status = EXCLUDED.blurred_face_status,
    face_validation_status = EXCLUDED.face_validation_status,
    covered_face_status = EXCLUDED.covered_face_status,
    face_matching_score = EXCLUDED.face_matching_score,
    source_provider = EXCLUDED.source_provider,
    source_reference = EXCLUDED.source_reference,
    raw_payload = EXCLUDED.raw_payload,
    active = EXCLUDED.active,
    updated_at = NOW();
