ALTER TABLE final_test_attempts
ADD COLUMN status VARCHAR(20) DEFAULT 'SUBMITTED',
ADD COLUMN start_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN submit_time TIMESTAMP WITH TIME ZONE;

ALTER TABLE final_test_attempts ALTER COLUMN score DROP NOT NULL;
ALTER TABLE final_test_attempts ALTER COLUMN passed DROP NOT NULL;
ALTER TABLE final_test_attempts ALTER COLUMN answers_json DROP NOT NULL;
