export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    COURSE_BROWSE: '/courses',
    COURSE_DETAIL: '/courses/:id',
    TEACHER_PROFILE: (teacherId: string) => `/teachers/${teacherId}`,
    ABOUT: '/about',
    HELP: '/help',
    TERMS: '/legal/terms',
    PRIVACY: '/legal/privacy',
    INSTRUCTOR_TERMS: '/legal/instructor-terms',
    REFUND_POLICY: '/legal/refund-policy',
    AI_NOTICE: '/legal/ai-notice',
    INSTRUCTOR_REVENUE_SHARE: '/help/instructors/revenue-share',
    INSTRUCTOR_ESCROW_PAYOUTS: '/help/instructors/escrow-and-payouts',
  },
  STUDENT: {
    DASHBOARD: '/student/dashboard',
    MY_COURSES: '/student/courses',
    BROWSE_COURSES: '/student/browse',
    WISHLIST: '/student/wishlist',
    COURSE_LEARN: (courseId: string) => `/student/courses/${courseId}/learn`,
    PAYMENTS: '/student/payments',
    WALLET: '/student/wallet',
    NOTIFICATIONS: '/student/notifications',
    PROFILE: '/student/profile',
    AI_CHAT: (courseId: string, lessonBlockId: string) =>
      `/student/courses/${courseId}/lesson-blocks/${lessonBlockId}/ai-chat`,
  },
  TEACHER: {
    DASHBOARD: '/teacher/dashboard',
    COURSES: '/teacher/courses',
    COURSE_CREATE: '/teacher/courses/new',
    COURSE_BUILDER: (draftId: string) => `/teacher/courses/${draftId}/builder`,
    WRITING_REVIEWS: '/teacher/writing-reviews',
    WRITING_REVIEW_DETAIL: (submissionId: string) => `/teacher/writing-reviews/${submissionId}`,
    KYC: '/teacher/kyc',
    WALLET: '/teacher/wallet',
    NOTIFICATIONS: '/teacher/notifications',
    PROFILE: '/teacher/profile',
  },
  ADMIN: {
    LOGIN: '/admin/login',
    FORGOT_PASSWORD: '/admin/forgot-password',
    RESET_PASSWORD: '/admin/reset-password',
    CHANGE_PASSWORD: '/admin/change-password',
    DASHBOARD: '/admin/dashboard',
    SYSTEM_SETTINGS: '/admin/settings',
    USERS: '/admin/users',
    COURSE_APPROVAL: '/admin/courses/approvals',
    WEEKLY_CHALLENGES: '/admin/weekly-challenges',
    KYC_REVIEW: '/admin/kyc',
    PAYOUTS: '/admin/payouts',
    VIOLATIONS: '/admin/violations',
    NOTIFICATIONS: '/admin/notifications',
    REFUND_REVIEW: '/admin/refunds',
    AUDIT_LOGS: '/admin/audit-logs',
  },
};
