export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    COURSE_BROWSE: '/courses',
    COURSE_DETAIL: '/courses/:id',
    TEACHER_PROFILE: (teacherId: string) => `/teachers/${teacherId}`,
    ABOUT: '/about',
  },
  STUDENT: {
    DASHBOARD: '/student/dashboard',
    MY_COURSES: '/student/courses',
    BROWSE_COURSES: '/student/browse',
    WISHLIST: '/student/wishlist',
    COURSE_LEARN: (courseId: string) => `/student/courses/${courseId}/learn`,
    PAYMENTS: '/student/payments',
    NOTIFICATIONS: '/student/notifications',
    PROFILE: '/student/profile',
    AI_CHAT: (courseId: string, lessonBlockId: string) =>
      `/student/courses/${courseId}/lesson-blocks/${lessonBlockId}/ai-chat`,
  },
  TEACHER: {
    DASHBOARD: '/teacher/dashboard',
    COURSES: '/teacher/courses',
    COURSE_CREATE: '/teacher/courses/new',
    COURSE_BUILDER: (draftId: string) => `/teacher/courses/${draftId}/builder`,
    WRITING_REVIEWS: '/teacher/writing-reviews',
    WRITING_REVIEW_DETAIL: (submissionId: string) => `/teacher/writing-reviews/${submissionId}`,
    KYC: '/teacher/kyc',
    WALLET: '/teacher/wallet',
    NOTIFICATIONS: '/teacher/notifications',
    PROFILE: '/teacher/profile',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    SYSTEM_SETTINGS: '/admin/settings',
    USERS: '/admin/users',
    TASK_QUEUE: '/admin/tasks/queue',
    COURSE_APPROVAL: '/admin/courses/approvals',
    KYC_REVIEW: '/admin/kyc',
    FINANCE: '/admin/finance',
    PAYOUTS: '/admin/payouts',
    NOTIFICATIONS: '/admin/notifications',
    REFUND_REVIEW: '/admin/refunds',
  },
};
