export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    COURSE_BROWSE: '/courses',
    COURSE_DETAIL: '/courses/:id',
    ABOUT: '/about',
  },
  STUDENT: {
    DASHBOARD: '/student/dashboard',
    MY_COURSES: '/student/courses',
    COURSE_LEARN: (courseId: string) => `/student/courses/${courseId}/learn`,
    PAYMENTS: '/student/payments',
    NOTIFICATIONS: '/student/notifications',
    PROFILE: '/student/profile',
  },
  TEACHER: {
    DASHBOARD: '/teacher/dashboard',
    COURSES: '/teacher/courses',
    COURSE_CREATE: '/teacher/courses/new',
    COURSE_BUILDER: (draftId: string) => `/teacher/courses/${draftId}/builder`,
    KYC: '/teacher/kyc',
    WALLET: '/teacher/wallet',
    NOTIFICATIONS: '/teacher/notifications',
    PROFILE: '/teacher/profile',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    SYSTEM_SETTINGS: '/admin/settings',
    USERS: '/admin/users',
    TASK_QUEUE: '/admin/tasks/queue',
    COURSE_APPROVAL: '/admin/courses/approvals',
    KYC_REVIEW: '/admin/kyc',
    FINANCE: '/admin/finance',
    NOTIFICATIONS: '/admin/notifications',
  },
};
